// http errors -- resource ids.

#define RC_BAD_REQUEST		400
#define RC_UNAUTHORIZED		401
#define RC_PAYMENT_REQUIRED	402
#define RC_FORBIDDEN		403
#define RC_NOT_FOUND		404
#define RC_METHOD_NOT_ALLOWED	405
#define RC_NOT_ACCEPTABLE	406
#define RC_REQUEST_TIMEOUT	407

#define RC_INTERNAL_SERVER_ERROR	500
#define RC_NOT_IMPLEMENTED	501
